import type { Establishment, EstablishmentCategory } from '@/types/establishments';

type EstablishmentScreenContent = {
  title: string;
  subtitle: string;
  mapLabel: string;
  ctaLabel: string;
  items: Establishment[];
};

export const establishmentContent: Record<EstablishmentCategory, EstablishmentScreenContent> = {
  centers: {
    title: 'Centros de atencion',
    subtitle: 'Opciones cercanas para recibir apoyo medico y orientacion inicial.',
    mapLabel: 'Mapa con mi ubicacion real y centros demo cercanos',
    ctaLabel: 'Actualizar ubicacion',
    items: [
      {
        id: 'center-1',
        name: 'Centro Medico Norte',
        distance: '1.2 km',
        eta: '6 min',
        status: 'Abierto 24 h',
        address: 'Av. Central 245',
        summary: 'Urgencias leves, orientacion general y consulta prioritaria.',
        markerLabel: '1',
        rating: 4.7,
        coordinate: { latitude: -34.6019, longitude: -58.3837 },
      },
      {
        id: 'center-2',
        name: 'Clinica Santa Maria',
        distance: '2.4 km',
        eta: '10 min',
        status: 'Abierto hasta 22:00',
        address: 'Calle Salud 88',
        summary: 'Consulta ambulatoria, pediatria y apoyo al viajero.',
        markerLabel: '2',
        rating: 4.5,
        coordinate: { latitude: -34.5958, longitude: -58.3893 },
      },
      {
        id: 'center-3',
        name: 'Unidad Medica Sur',
        distance: '3.1 km',
        eta: '13 min',
        status: 'Turnos disponibles',
        address: 'Paseo del Rio 310',
        summary: 'Atencion general, laboratorio basico y derivacion rapida.',
        markerLabel: '3',
        rating: 4.3,
        coordinate: { latitude: -34.6087, longitude: -58.3748 },
      },
    ],
  },
  pharmacies: {
    title: 'Farmacias cercanas',
    subtitle: 'Puntos de apoyo rapido para medicamentos y articulos esenciales.',
    mapLabel: 'Mapa con mi ubicacion real y farmacias demo cercanas',
    ctaLabel: 'Actualizar ubicacion',
    items: [
      {
        id: 'pharmacy-1',
        name: 'Farmacia Central',
        distance: '450 m',
        eta: '5 min',
        status: 'Abierta ahora',
        address: 'Plaza Mayor 14',
        summary: 'Medicamentos generales, guardia nocturna y articulos basicos.',
        markerLabel: '1',
        rating: 4.8,
        coordinate: { latitude: -34.6028, longitude: -58.3819 },
      },
      {
        id: 'pharmacy-2',
        name: 'Farmacia del Viajero',
        distance: '1.1 km',
        eta: '7 min',
        status: 'Abierta hasta 23:00',
        address: 'Av. Estacion 102',
        summary: 'Enfoque en primeros auxilios, higiene y recetas frecuentes.',
        markerLabel: '2',
        rating: 4.6,
        coordinate: { latitude: -34.5979, longitude: -58.3868 },
      },
      {
        id: 'pharmacy-3',
        name: 'Farmacia Barrio Verde',
        distance: '1.9 km',
        eta: '9 min',
        status: 'Entrega en el dia',
        address: 'Calle Parque 57',
        summary: 'Medicacion comun, insumos y asesoramiento breve.',
        markerLabel: '3',
        rating: 4.4,
        coordinate: { latitude: -34.6072, longitude: -58.3766 },
      },
    ],
  },
  hospitals: {
    title: 'Hospitales con guardia',
    subtitle: 'Opciones cercanas para atencion inmediata y guardia activa.',
    mapLabel: 'Mapa con mi ubicacion real y guardias demo cercanas',
    ctaLabel: 'Actualizar ubicacion',
    items: [
      {
        id: 'hospital-1',
        name: 'Hospital General San Martin',
        distance: '1.8 km',
        eta: '8 min',
        status: 'Guardia 24 h',
        address: 'Av. Libertad 520',
        summary: 'Guardia general, trauma, estudios basicos y laboratorio inicial.',
        markerLabel: '1',
        rating: 4.6,
        coordinate: { latitude: -34.5994, longitude: -58.3841 },
      },
      {
        id: 'hospital-2',
        name: 'Hospital de Urgencias del Sur',
        distance: '3.2 km',
        eta: '12 min',
        status: 'Guardia adultos y pediatria',
        address: 'Bv. Sur 1180',
        summary: 'Atencion de urgencias, imagenes y derivacion de alta complejidad.',
        markerLabel: '2',
        rating: 4.4,
        coordinate: { latitude: -34.5962, longitude: -58.3919 },
      },
      {
        id: 'hospital-3',
        name: 'Hospital Metropolitano Norte',
        distance: '4.1 km',
        eta: '15 min',
        status: 'Guardia y terapia intensiva',
        address: 'Calle Primera Junta 77',
        summary: 'Emergencias mayores, cardiologia y neurologia de urgencia.',
        markerLabel: '3',
        rating: 4.5,
        coordinate: { latitude: -34.6103, longitude: -58.3781 },
      },
    ],
  },
};
